2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Configure stats pid to 6328
2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Özdemir\.config\wandb\settings
2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\settings
2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-27 15:59:19,028 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-27 15:59:19,029 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-27 15:59:19,029 INFO    MainThread:6328 [wandb_init.py:_log_setup():524] Logging user logs to b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\run-20231127_155919-ndj0y640\logs\debug.log
2023-11-27 15:59:19,029 INFO    MainThread:6328 [wandb_init.py:_log_setup():525] Logging internal logs to b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\run-20231127_155919-ndj0y640\logs\debug-internal.log
2023-11-27 15:59:19,029 INFO    MainThread:6328 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000020874A7AD50>
2023-11-27 15:59:19,030 INFO    MainThread:6328 [wandb_init.py:init():564] calling init triggers
2023-11-27 15:59:19,030 INFO    MainThread:6328 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-11-27 15:59:19,030 INFO    MainThread:6328 [wandb_init.py:init():614] starting backend
2023-11-27 15:59:19,030 INFO    MainThread:6328 [wandb_init.py:init():618] setting up manager
2023-11-27 15:59:19,039 INFO    MainThread:6328 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-11-27 15:59:19,044 INFO    MainThread:6328 [wandb_init.py:init():624] backend started and connected
2023-11-27 15:59:19,055 INFO    MainThread:6328 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-11-27 15:59:19,056 INFO    MainThread:6328 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-27 15:59:19,056 INFO    MainThread:6328 [wandb_init.py:init():716] updated telemetry
2023-11-27 15:59:19,114 INFO    MainThread:6328 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-27 15:59:19,640 ERROR   MainThread:6328 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-27 15:59:19,882 ERROR   MainThread:6328 [wandb_init.py:init():1184] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-27 16:01:13,912 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-27 16:01:13,912 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Configure stats pid to 6328
2023-11-27 16:01:13,912 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Özdemir\.config\wandb\settings
2023-11-27 16:01:13,912 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\settings
2023-11-27 16:01:13,912 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-27 16:01:13,913 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-27 16:01:13,913 INFO    MainThread:6328 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-27 16:01:13,913 INFO    MainThread:6328 [wandb_init.py:_log_setup():524] Logging user logs to b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\run-20231127_160113-7umofzto\logs\debug.log
2023-11-27 16:01:13,914 INFO    MainThread:6328 [wandb_init.py:_log_setup():525] Logging internal logs to b:\Dosya\Kodlar\Sem-Images-Classification\notebooks\wandb\run-20231127_160113-7umofzto\logs\debug-internal.log
2023-11-27 16:01:13,914 INFO    MainThread:6328 [wandb_init.py:init():564] calling init triggers
2023-11-27 16:01:13,914 INFO    MainThread:6328 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-11-27 16:01:13,914 INFO    MainThread:6328 [wandb_init.py:init():614] starting backend
2023-11-27 16:01:13,914 INFO    MainThread:6328 [wandb_init.py:init():618] setting up manager
2023-11-27 16:01:13,923 INFO    MainThread:6328 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-11-27 16:01:13,925 INFO    MainThread:6328 [wandb_init.py:init():624] backend started and connected
2023-11-27 16:01:13,934 INFO    MainThread:6328 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-11-27 16:01:13,934 INFO    MainThread:6328 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-27 16:01:13,934 INFO    MainThread:6328 [wandb_init.py:init():716] updated telemetry
2023-11-27 16:01:14,005 INFO    MainThread:6328 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-27 16:02:44,909 ERROR   MainThread:6328 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-11-27 16:02:44,982 ERROR   MainThread:6328 [wandb_init.py:init():1184] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-11-27 16:16:28,817 WARNING MsgRouterThr:6328 [router.py:message_loop():77] message_loop has been closed
